# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 21:57
from __future__ import unicode_literals

import administration.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cloudAddresss', models.CharField(max_length=64)),
                ('bucketName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='companyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='fileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ext', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('storage', models.IntegerField()),
                ('months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profilePic', models.CharField(max_length=100)),
                ('dateAdded', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1, validators=[administration.validators.genderValidator])),
                ('isActive', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('isGoogleLinked', models.BooleanField(default=False)),
                ('googleUserId', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=20, validators=[administration.validators.minPhoneLength])),
                ('isBlocked', models.BooleanField(default=False)),
                ('lastActive', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userGroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True, null=True)),
                ('lastModified', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.User')),
            ],
        ),
        migrations.CreateModel(
            name='userSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.cloud')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.subscriptionPlan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='partOfGroups', through='administration.userGroupInfo', to='administration.User'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.User'),
        ),
        migrations.AddField(
            model_name='cloud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.User'),
        ),
        migrations.AlterUniqueTogether(
            name='usergroupinfo',
            unique_together=set([('user', 'group')]),
        ),
    ]
