# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud',
            old_name='cloudAddresss',
            new_name='cloudAddress',
        ),
    ]
