# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authToken', models.CharField(max_length=128, unique=True)),
                ('isExpired', models.BooleanField(default=False)),
                ('createdTime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.User')),
            ],
        ),
    ]
