# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-15 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('path', models.CharField(max_length=100)),
                ('isExpired', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('addedTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('expiryTime', models.DateTimeField(blank=True, null=True)),
                ('cloud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.cloud')),
            ],
        ),
    ]
